Intake
cavineers/RobotCode2020 pull request #6
Opened 2020-01-16 17:37 UTC by Sounder317

Ready to merge got talon working.

2020-01-17 16:39 UTC, brycecary requested changes
Please fix your formatting according to the below standards:

https://cavineers.github.io/CodeStandards/docs/java-indentation.html

2020-01-18 03:34 UTC, Sounder317 commented
I think I fixed the formatting

2020-01-21 18:55 UTC, brycecary commented on src/main/java/frc/robot/subsystems/Intake.java
>  package frc.robot.subsystems;
This is still showing 2 space indentation for me. If you don't mind switching it to 4 spaces.
https://cavineers.github.io/CodeStandards/docs/java-indentation.html

2020-01-21 19:03 UTC, brycecary requested changes
1. Can you fix the spacing \([Reference](https://cavineers.github.io/CodeStandards/docs/java-indentation.html)\)
1. Can you remove OI from the imports, a subsystem shouldn't need to call it
1. `ControlMode.PercentOutput` must be between the values of [-1, 1] \([Reference](http://www.ctr-electronics.com/downloads/api/java/html/enumcom_1_1ctre_1_1phoenix_1_1motorcontrol_1_1_control_mode.html#adc64ac712cda8e44241a9c476dbff22e)\)
1. The logic seems a little much. Try simplifying it if you can.

2020-01-24 02:45 UTC, closed without merging